lang: ru-RU
encoding: utf-8
url: https://progmsk.github.io
permalink: pretty
highlighter: rouge
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed

paginate: 2
paginate_path: "/:num"

sass:
  style: :compressed
